### PR TITLE
Title settings → Ordered checkbox

### PR DESCRIPTION
**Pull request by fearnlj01**
I'll rebase this branch into a single commit when it's eventually ready for review, but figured it best to open a draft PR now that the html/js implementation is ___hopefully___ complete...

Unless future commits render the plugin unable to load, the client side changes should be able to be previewed (with saving/loading the settings being non-functional).

### CODE REVIEW

**Comment by fearnlj01** [comment]
And for the sake of the curious who don't fancy delving too deep into things... The following screenshots summarise what the settings will be changing to with this PR.

image

image

**Comment by revam** [comment]
sorry, forgot to mention, only the options should had "main" replaced by "default", the _main_ title we choose the selectors for will still be called the main title. :pensive:

**Comment by fearnlj01** [comment]
> sorry, forgot to mention, only the options should had "main" replaced by "default", the _main_ title we choose the selectors for will still be called the main title. 😔

Realised the same thing after uploading the images... I got a little overzealous with the Find & Replace tool 🙊

**Comment by revam** [comment]
fast-n-dirty preview (mind the capitalization. also, every word that is not a name (e.g. Shoko, AniDB, TMDB) or the first word in the sentence should not be capitalized);
image

**Comment by revam** [comment]
Also also, don't mention Shokofin **at all** in the config page.

**Comment by fearnlj01** [comment]
For the sake of putting an image to the previous commit...

image

**Comment by revam** [comment]
Can you remove the lines where it says the overrides are applied even if they aren't enabled?

**Comment by fearnlj01** [comment]
I've done what limited testing I can with my library and it's working as _I_ expect at the very least.

Obviously with the quantity of changes, the plugin will have drastically different behaviour for generating titles albeit arguarbly more expected behaviour.


Hopefully the way I've done this keeps it satisfactorily easy to adapt when any additional shoko powered providers are implemented :)

**Pull request merged**
